
name: Node.js CI  # This ensures the workflow is named "Node.js CI" in GitHub Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Jest Tests on Node.js ${{ matrix.node-version }}  # Job name displayed in GitHub Actions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Display Node.js version
        run: node -v  # Logs the Node.js version to confirm it's using the right one
